# Generated by Django 4.2.11 on 2025-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_rename_avg_rating_watchlist_avg_rating_per_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
