# Generated by Django 4.2.11 on 2025-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_watchlist_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='total_avg_ratings',
            field=models.FloatField(default=0),
        ),
    ]
